---
spring:
  application:
    name: age-additional-batch
  messages:
    encoding: UTF-8
  jackson:
    time-zone: "Asia/Tokyo"

logging:
  level:
    web: debug

---
# -Dspring.profiles.activeを指定しなかった場合のデフォルトプロファイル
# 年齢加算バッチとしてはh2をデフォルト使用とする(インメモリなのでデータを保持しなくなる)
spring:
  profiles:
    default: local