DROP TABLE IF EXISTS USER;
CREATE TABLE USER
(
    USER_ID     INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    LAST_NAME   VARCHAR2(20)            NOT NULL,
    FIRST_NAME  VARCHAR2(20)            NOT NULL,
    AGE         INTEGER                 NOT NULL,
    BIRTH_DAY   DATE                    NOT NULL,
    CREATED_AT  DATE    DEFAULT CURRENT_DATE NOT NULL,
    CREATE_USER VARCHAR2(50),
    UPDATE_AT   DATE    DEFAULT CURRENT_DATE NOT NULL,
    UPDATE_USER VARCHAR2(50),
    DELETE_FLG  CHAR(1) DEFAULT '0'     NOT NULL
);

COMMENT ON COLUMN USER.USER_ID IS 'ユーザーID';
COMMENT ON COLUMN USER.LAST_NAME IS '苗字';
COMMENT ON COLUMN USER.FIRST_NAME IS '名前';
COMMENT ON COLUMN USER.AGE IS '年齢';
COMMENT ON COLUMN USER.BIRTH_DAY IS '誕生日';
COMMENT ON COLUMN USER.CREATED_AT IS 'レコード作成日';
COMMENT ON COLUMN USER.CREATE_USER IS 'レコード作成者';
COMMENT ON COLUMN USER.UPDATE_AT IS 'レコード更新日';
COMMENT ON COLUMN USER.UPDATE_USER IS '最終更新者';
COMMENT ON COLUMN USER.DELETE_FLG IS '論理削除';