-- H2使用時のUSERテーブル投入データ
INSERT INTO ACCOUNT(LAST_NAME, FIRST_NAME, AGE, BIRTH_DAY, CREATE_USER, UPDATE_USER,DELETE_FLG)
VALUES ('テスト','一郎',20,DATEADD('yyyy',-24,CURRENT_DATE) ,'年齢加算バッチ','年齢加算バッチ','0');
INSERT INTO ACCOUNT(LAST_NAME, FIRST_NAME, AGE, BIRTH_DAY, CREATE_USER, UPDATE_USER,DELETE_FLG)
VALUES ('テスト','次郎',20,DATEADD('yyyy',-21,CURRENT_DATE) ,'年齢加算バッチ','年齢加算バッチ','0');
INSERT INTO ACCOUNT(LAST_NAME, FIRST_NAME, AGE, BIRTH_DAY, CREATE_USER, UPDATE_USER,DELETE_FLG)
-- 以下は対象外想定データ
INSERT INTO ACCOUNT(LAST_NAME, FIRST_NAME, AGE, BIRTH_DAY, CREATE_USER, UPDATE_USER,DELETE_FLG)
VALUES ('テスト','対象外',20,DATEADD('yyyy',-24,CURRENT_DATE -1) ,'年齢加算バッチ','年齢加算バッチ','0');